# Generated by Django 4.1.7 on 2023-07-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
        migrations.RemoveField(
            model_name='users',
            name='gender',
        ),
    ]
